#pragma once

#define TAPPING_TERM 200
// #define TAPPING_TERM_PER_KEY
#define ENCODER_DIRECTION_FLIP
#define RGB_MATRIX_DEFAULT_VAL 127
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 150
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_TYPING_HEATMAP
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#define RGB_TRIGGER_ON_KEYDOWN
#define RGB_MATRIX_TYPING_HEATMAP_INCREASE_STEP 16
#define RGB_MATRIX_TYPING_HEATMAP_AREA_LIMIT 32
#define RGB_MATRIX_TYPING_HEATMAP_SPREAD 50
#define RGB_MATRIX_TYPING_HEATMAP_DECREASE_DELAY_MS 5
// #define HOLD_ON_OTHER_KEY_PRESS
// #define HOLD_ON_OTHER_KEY_PRESS_PER_KEY